### PR TITLE
add vocab_dataLevel excel file for the new vocab about eLTER data levels

### PR DESCRIPTION
**Pull request by oggioniale**

### CODE REVIEW

**Comment by dalito** [comment]
You can manually trigger the failed workflow to run again if you don't have changes to push that would re-trigger.

**Comment by dalito** [comment]
I saw that you added a user to `IDranges.toml` but there is a typo: 

`[[vocabs.dataLevel.idrange]]` --> `[[vocabs.dataLevel.id_range]]` (missing underscore)

**Comment by oggioniale** [comment]
> I saw that you added a user to `IDranges.toml` but there is a typo:
> 
> `[[vocabs.dataLevel.idrange]]` --> `[[vocabs.dataLevel.id_range]]` (missing underscore)

True! I change it but nothing change.

**Comment by dalito** [comment]
Could you try to rebase this PR on the last commit? (or close this PR and create a new one)

The problem is probably that this PR-branch has still the old `IDranges.toml`. Without a rebase the later changes from `main`branch have no effect.

**Pull request closed without merging**
